def arr_to_dict(arr):
    #Translates a numpy array to a dict with keys as array column indices 
    #and values as array values. Useful for shank/electrode data handling.
    #Note: if used on an array that was generated by dict_to_arr, the 
    #resulting Dict will likely not be identically indexed as the first
    #Dict since dict_to_arr writes arrays without actual regard to index.
    #***may want to fix this
    
    import numpy as np
    
    Dict = {}
    for x in range(arr.shape[1]):
        Dict.update({x: arr[:, x]})
    return Dict
