execfile('BuzsakiSession.py')
execfile('write_nwb.py')
#session = Session('ec013.156')
#session.load_LFPdata()
#lfp = session.get_shankLFP(0, True)
#csd = session.get_CSD(4)

write_nwb('ec012ec.356')
write_nwb('ec013.156')
write_nwb('ec013.157')
write_nwb('ec013.756')
write_nwb('ec013.965')
write_nwb('ec014.468')
write_nwb('ec014.639')
write_nwb('ec016.234')
write_nwb('ec016.749')

#os.chdir(cwd)
#execfile('dict_to_arr.py')
#execfile('plot_Signal.py')
#execfile('filter_LFP.py')
#execfile('hilbert.py')
#execfile('dict_to_arr.py')
#t = session.LFP_timestamps
#filt = filter_LFP(t, lfp, session.LFP_rate, 'theta', False)
#phase, amp, hilbData = hilbert(filt)
